### ISSUE TITLE
Type Error When Deploying

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/upstash-redis-level#6]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When deploying I got  the following error.

```
./tina/database.ts:33:9
--
10:23:19.515 | Type error: Type 'import("/vercel/path0/node_modules/@upstash/redis/nodejs").Redis' is not assignable to type 'import("/vercel/path0/node_modules/upstash-redis-level/node_modules/@upstash/redis/types/platforms/nodejs").Redis'.
10:23:19.515 | Property 'client' is protected but type 'Redis' is not a class derived from 'Redis'.
10:23:19.515 |  
10:23:19.515 | 31 \|       databaseAdapter: new RedisLevel({
10:23:19.515 | 32 \|         namespace: branch,
10:23:19.515 | > 33 \|         redis: new Redis({
10:23:19.515 | \|         ^
10:23:19.515 | 34 \|           url: process.env.KV_REST_API_URL!,
10:23:19.515 | 35 \|           token: process.env.KV_REST_API_TOKEN!,
10:23:19.516 | 36 \|         }),
10:23:19.637 | error Command failed with exit code 1.
```

This is because I was on the latest version of `@upstash/redis` but `upstash-redis-level` has a direct dependency on an older version which caused a type miss match. 

### Reproduction

https://www.loom.com/share/219a286cd0294e249048a205770c6a92?sid=6809b2e5-6045-4f2f-ac2a-7a306fb2044a

### System Info

```shell
"upstash-redis-level": "^1.0.0"
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/tinacms/upstash-redis-level/issues) that reports the same bug.

**Comment by kldavis4** [comment]
is this dependent on the nextjs version?

**Comment by logan-anderson** [comment]
> is this dependent on the nextjs version?

I don't see why it would be. 

This is the demo repo I was using: https://github.com/tinacms/next-visual-kv-demo (I have fixed the error but you can reproduce it by updating to the latest `@upstash/redis` version)

**Comment by kldavis4** [comment]
I see the problem - you are using conflicting versions of @upstash/redis and upstash-redis-level. This works fine: https://github.com/tinacms/tina-self-hosted-demo/blob/self-host/package.json#L39

I'll upgrade the version, but I'm deliberately keeping the @upstash/redis version to the same version as @vercel/kv, which is currently behind the latest @upstash/redis, so you may still run into issues if you try to use the latest @upstash/redis

**Comment by kldavis4** [comment]
published upstash-redis-level@1.1.0 which is compatible with @upstash/redis@1.24.3

**Comment by kldavis4** [comment]
Just made the changes we discussed. Here is the commit in the tina-self-hosted-demo branch: https://github.com/tinacms/tina-self-hosted-demo/commit/29edaa212905624a1caf5dea5c86c6e87feee0c4

**Comment by logan-anderson** [comment]
@kldavis4 Sounds good. I can update the docs / init

**Comment by logan-anderson** [comment]
Updated the docs and init

Pr for init is here: https://github.com/tinacms/tinacms/pull/4339
